### ISSUE TITLE
App not working on mac safari

### ISSUE THREAD

**Issue by cuzzea** [AngellusMortis/boundlexx-ui#1]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/639295/97203921-23655280-17be-11eb-98de-2819317474a2.png">

I am looking into it, maybe I can push a fix for it.

**Comment by AngellusMortis** [comment]
I should be able to fix this specific error (it just looks `matchMedia` does not exist on Safari), but I do not own any Apple products and unless someone wants to contribute who does, I cannot promise any support for Apple devices. 

Firefox and Chromium based browser (Chrome, Opera, Microsoft Edge, etc.) are the only official supported browsers because those are the only ones I have access to. 

EDIT: Mostly a note for me, but here are the details of what is breaking and why: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#Browser_compatibility

It looks like it should work in Safari 14+ out of the box as well.

**Comment by AngellusMortis** [comment]
@cuzzea, it is awesome you already made a PR, but I think I already fixed it. can you test to verify?

**Comment by cuzzea** [comment]
I am up to date with master, and I am getting that error. Also unrelated, calls to https://api.boundlexx.app/api/v2/schema/?format=openapi-json give `504 Gateway Time-out`

**Comment by AngellusMortis** [comment]
I have not pushed the changes upstream yet. Check on the live site.

Also, yeah, sometimes the schema times out after I do an update on the backend. I forget to always make sure it is cached.

**Comment by cuzzea** [comment]
works. 👍

**Comment by AngellusMortis** [comment]
Thanks! I pushed the changes upstream. Thanks for helping figuring out the issue. 

@The-Garden-Gnome and I both are not the most experience with Typescript or React, so definitely feel free to make PRs for anything you want to clean up or add!

**Comment by cuzzea** [comment]
tbh, I am more of an angular guy, but I like boundless and I like coding, so I will try to keep active around here 👍

**Comment by AngellusMortis** [comment]
I am actually more of an Ember person myself (well, really much more backend, I still do not even have proper CI or anything set up on this project yet...), but React is what is "popular" so I figured it would be good as learning experience.
